version: '3'

tasks:
  # 停止容器
  stop:
    cmds:
      - docker stop $(docker ps -q)

  # 建立網路 home
  network:
    cmds:
      # 檢查網路是否存在, 不然就建立它
      - |
        if ! docker network ls | grep -qw home; then
          docker network create home
        fi

  # 啟動資料庫
  db:
    deps: [ network ]
    cmds:
      # 啟動 MySQL
      - docker rm -f -v home-mysql || true
      - docker image rm home-mysql || true
      - docker build -t home-mysql -f MySQL/Dockerfile .
      - docker volume rm dbmysql-volume || true
      - |
        case "$(uname)" in
          MINGW*|CYGWIN*|MSYS*)
            echo "Windows"
            docker run -d --name home-mysql --network home -v "C:\data\mysql\:/var/lib/mysql" -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root home-mysql
            ;;
          *)
            echo "Linux"
            docker run -d --name home-mysql --network home -v /data/mysql:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root home-mysql
            ;;
        esac

  # 啟動 Nginx
  nginx:
    deps: [ network ]
    cmds:
      - docker rm -f -v home-nginx || true
      - docker image rm home-nginx || true
      - docker build -t home-nginx -f Nginx/Dockerfile .
      - |
          case "$(uname)" in
            MINGW*|CYGWIN*|MSYS*)
              echo "Windows"
              docker run -d --name home-nginx --network home -v "C:\data:/data" -p 80:80 -p 443:443 -p 8080:8080 home-nginx
              ;;
            *)
              echo "Linux"
              docker run -d --name home-nginx --network home -v /data:/data -p 80:80 -p 443:443 -p 8080:8080 home-nginx
              ;;
          esac
      - docker exec home-nginx mkdir -p /data/nginx/conf.d
      - docker exec home-nginx mkdir -p /data/nginx/log
      - docker exec home-nginx mkdir -p /data/nginx/www

  # 啟動 PHP
  php:
    deps: [ network ]
    cmds:
      - docker image rm home-php || true
      - docker rm -f -v home-php || true
      - docker build -t home-php -f PHP/Dockerfile .
      - |
        case "$(uname)" in
          MINGW*|CYGWIN*|MSYS*)
            echo "Windows"
            docker run -d --name home-php --network home -v "C:\data\:/data" -p 9000:9000 home-php
            ;;
          *)
            echo "Linux"
            docker run -d --name home-php --network home -v /data:/data -p 9000:9000 home-php
            ;;
        esac

  # 啟動 WordPress
  wordpress:
    deps: [ network ]
    cmds:
      - docker exec home-nginx rm -rf /data/wordpress
      - docker cp WordPress/wordpress6.6.1 home-nginx:/data/
      - docker exec home-nginx mv /data/wordpress6.6.1 /data/wordpress
      - docker exec home-nginx rm -rf /data/nginx/conf.d/wordpress.conf
      - docker cp WordPress/wordpress.conf home-nginx:/data/nginx/conf.d/
      - docker exec home-nginx mkdir -p /data/nginx/log/wordpress.evonne-chen.com/
      - docker exec home-nginx rm -rf /etc/nginx/conf.d/default.conf
      - docker restart home-nginx

  # 啟動 Jenkins
  jenkins:
    deps: [ network ]
    cmds:
      - docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17
