version: '3'

tasks:
  # 停止容器
  stop:
    cmds:
      - docker stop $(docker ps -q)

  # 啟動資料庫
  wordpress:
    cmds:
      # 檢查網路是否存在, 不然就建立它
      - |
        if ! docker network ls | grep -qw home; then
          docker network create home
        fi
      # 啟動mysql
      - docker build -t home-mysql -f MySQL/Dockerfile .
      - docker rm -f -v home-mysql || true
      - docker volume rm dbmysql-volume || true
      - docker run -d --name home-mysql --network home -v dbmysql-volume:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root home-mysql
      # 啟動 wordpress
      - docker build -t home-wordpress -f WordPress/Dockerfile .
      - docker stop home-wordpress || true
      - docker rm home-wordpress || true
      - docker run --name home-wordpress --network home -p 8080:80 -d home-wordpress
      # 清除懸空鏡像
      - docker image prune -f
